import { escapeHtml } from '../assets/js/utils.js';
import { issueStats } from '../assets/js/progress.js';
import { isOptionalEntry } from '../assets/js/data-model.js';
import { SPECIAL_COLLECTIONS } from '../data/special-collections.js';

export function renderCompletedLibrary(models = []) {
  const completed = models.flatMap(model => [...model.entries.values()].filter(entry => issueStats(entry.issues || []).complete).map(entry => ({ model, entry })));
  const completedEvents = models.flatMap(model => [...model.events.values()].filter(event => issueStats(event.chapters || []).complete).map(event => ({ model, event })));
  const completedSpecials = SPECIAL_COLLECTIONS.filter(item => issueStats(item.issues || []).complete);
  return `<section class="page-hero"><span class="eyebrow">YOUR FINISHED SHELF</span><h1>Completed Library</h1><p>Completed arcs and events remain available here even when the reading routes automatically hide them.</p><div class="library-summary"><strong>${completed.length}</strong> arcs · <strong>${completedEvents.length}</strong> events · <strong>${completedSpecials.length}</strong> special-shelf works</div></section>
  <section class="section-shell"><div class="section-heading"><div><span class="eyebrow">COMPLETED ARCS</span><h2>${completed.length} finished</h2></div></div>${completed.length ? `<div class="completed-grid">${completed.map(({model,entry}) => `<article class="completed-card"><div><span>${escapeHtml(model.label)} · ${escapeHtml(model.routes.get(entry.routeId)?.shortTitle || '')}</span><h3>${escapeHtml(entry.title)}</h3><small>${escapeHtml((entry.writers || []).join(', '))}${isOptionalEntry(entry)?' · Optional':''}</small></div><a class="secondary-button compact-button" href="#/route/${escapeHtml(model.id)}/${escapeHtml(entry.routeId)}">Open route</a></article>`).join('')}</div>` : '<div class="empty-state">Complete an arc and it will appear here.</div>'}</section>
  <section class="section-shell"><div class="section-heading"><div><span class="eyebrow">COMPLETED EVENTS</span><h2>${completedEvents.length} finished</h2></div></div>${completedEvents.length ? `<div class="completed-grid">${completedEvents.map(({model,event}) => `<article class="completed-card event-completed-card"><div><span>${escapeHtml(model.label)} · ${escapeHtml(event.year)}</span><h3>${escapeHtml(event.title)}</h3><small>${event.chapters.length} chapters</small></div><a class="secondary-button compact-button" href="#/event/${escapeHtml(model.id)}/${escapeHtml(event.id)}">Open event</a></article>`).join('')}</div>` : '<div class="empty-state">Completed events will remain visible here.</div>'}</section>
  <section class="section-shell"><div class="section-heading"><div><span class="eyebrow">ELSEWORLDS & COLLABORATIONS</span><h2>${completedSpecials.length} finished</h2></div></div>${completedSpecials.length ? `<div class="completed-grid">${completedSpecials.map(item => `<article class="completed-card special-completed-card"><div><span>${escapeHtml(item.section === 'elseworlds' ? 'Elseworlds / Black Label' : 'Collaborations')} · ${escapeHtml(item.years)}</span><h3>${escapeHtml(item.title)}</h3><small>${escapeHtml((item.writers || []).join(', '))}</small></div><a class="secondary-button compact-button" href="#/specials/${escapeHtml(item.section)}">Open shelf</a></article>`).join('')}</div>` : '<div class="empty-state">Completed Elseworlds and collaborations will appear here.</div>'}</section>`;
}
